### ISSUE TITLE
мега баг =)

### ISSUE THREAD

**Issue by DimaTrushin** [venikman1/simple_algebra_library#6]
https://github.com/venikman1/simple_algebra_library/blob/03579ba74e2434c164033d47d6305278bcccdea3/headers/algorithms.h#L174
Надо
 for (size_t i = 0; i < divisors.size() && !divider.is_zero(); ++i)
вместо
 for (size_t i = 0; i < divisors.size() && not divider.is_zero(); ++i)
Я реально думал, что у меня глюки. Еле нашел. Понятия не имею, как оно у тебя компилируется =)

Еще вместо gmp.hpp пришлось использовать cpp_int.hpp. Ибо библиотеку gmp надо было собирать руками.

**Comment by venikman1** [comment]
Спасибо, поправил

**Comment by venikman1** [comment]
> Еще вместо gmp.hpp пришлось использовать cpp_int.hpp. Ибо библиотеку gmp надо было собирать руками.

Не вызвало больших затруднений?

**Comment by DimaTrushin** [comment]
Я просто не стал ее собирать. =)

**Comment by venikman1** [comment]
> Я реально думал, что у меня глюки. Еле нашел. Понятия не имею, как оно у тебя компилируется 

Вроде бы GCC специально зарезервировал эти операторы, поэтому и компилировалось. Похоже, это на меня так сильно питон влияет.
